### ISSUE TITLE
Merge changes from ASL fork

### ISSUE THREAD

**Issue by whart222** [ampl/asl#10]
In a fork of this repository (https://github.com/whart222/asl), I've prototyped two changes:

1. Configuration options to enable building of shared object libraries

2. A change to jac0dim.c to avoid calling exit() with an empty *.nl file.

I'm not sure whether these are implemented in a form that is suitable for a PR.

**Comment by glebbelov** [comment]
Concerning the CMake, please don’t address external projects. Probably you
can adjust Coek’s settings in the parent CMake. Moreover please use capital
letters for BUILD_SHARED_LIBS.

About the return_nofile option we are having some internal debates which we
hope to resolve. ASL is a library and should not exit() uncontrollably.

Чт, 16 марта 2023 г. в 7:55 AM, Bob Fourer ***@***.***>:

**Comment by whart222** [comment]
@glebbelov The change w.r.t. building shared objects is not specific to an external project.  Rather, I was adding support for building shared objects.

I just tried using BUILD_SHARED_LIBS on the main branch, and it doesn't seem to work.

**Comment by glebbelov** [comment]
@whart222 there is the following line:

  set_target_properties(coek PROPERTIES POSITION_INDEPENDENT_CODE ${BUILD_SHARED_LIBS})

it causes an error when configuring without Coek.

**Comment by whart222** [comment]
@glebbelov I've made the changes you suggested.

**Comment by glebbelov** [comment]
@whart222 I added BUILD_SHARED_LIBS on master, please see if it works.
