### ISSUE TITLE
ARM MacOS Build

### ISSUE THREAD

**Issue by yasirroni** [ampl/asl#18]
Is there any information on how to install this on ARM MacOS M1?

**Comment by jurgen-lentz** [comment]
You can use the same command as for MacOS intel (x86_64) to build asl ARM MacOS M1 e.g.
```
mkdir build
cd build
cmake .. -DBUILD_CPP=ON -DBUILD_EXAMPLES=ON -DBUILD_F2C=ON
make -j
```
(if you build it on MacOS M1).
