### ISSUE TITLE
request a release

### ISSUE THREAD

**Issue by chenrui333** [ampl/asl#21]
Since [asl got removed mp](https://github.com/ampl/mp/tree/dcf32ab0f2b805f23fae4b3a57a2b1e360d86680), and there is a new mp release, it might be better to cut a new release so that some downstream projects can package asl. Thanks!

**Comment by glebbelov** [comment]
Just tagged: https://github.com/ampl/asl/releases/tag/v1.0.0

**Comment by chenrui333** [comment]
Thanks @glebbelov!
